# # apiVersion: v1
# # kind: ConfigMap
# # metadata:
# #   name: blackbox-exporter-config
# #   namespace: monitoring
# # data:
# #   config.yaml: |
# #     scrape_configs:
# #       - job_name: 'blackbox'
# #         metrics_path: /probe
# #         params:
# #           module: [http_2xx]
# #         static_configs:
# #           - targets:
# #             - http://polygon-rpc-app.default.svc.cluster.local:5001/block_number
# #         relabel_configs:
# #           - source_labels: [__address__]
# #             target_label: __param_target
# #           - target_label: instance
# #             replacement: blackbox-exporter
# #           - source_labels: [__param_target]
# #             target_label: __address__
# #             replacement: blackbox-exporter.monitoring.svc.cluster.local:9115

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: blackbox-exporter-config
#   namespace: monitoring
# data:
#   config.yml: |
#     modules:
#       http_endpoint:
#         prober: http
#         timeout: 5s
#         http:
#           valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
#           valid_status_codes: [200, 204]
#           no_follow_redirects: false
#           preferred_ip_protocol: "ip4"

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_endpoint]
        static_configs:
          - targets:
            - http://polygon-rpc-app.default.svc.cluster.local:5001/block_number
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: instance
            replacement: blackbox-exporter
          - source_labels: [__param_target]
            target_label: __address__
            replacement: "blackbox-exporter.monitoring.svc.cluster.local:9115"
