# service-monitor.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: polygon-rpc-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: polygon-rpc-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - interval: 60s
      port: http
      path: /metrics
      scheme: http
  targetLabels:
    - service
    - pod
